### ISSUE TITLE
Sprite edit tab should hide if the sprite sheet data page/image is protected

### ISSUE THREAD

**Issue by KnightMiner** [Majr-/SpriteEdit#2] opened 2015-09-10 00:55 UTC
While we don't have any fully protected sprite sheets on the Minecraft Wiki, there are a few protected by cascading protection (like ItemSprite), and it would be better if the "Edit sprite" tab was simply removed if the user cannot edit the sprite sheet page, rather than relying on the "cannot edit page" error at the end.

**Comment by Majr25** [comment] 2015-09-11 15:42
That would be ideal. Unfortunately, MediaWiki doesn't make it easy to find out if you can perform an action on a title. Instead of simply asking the API "can I X page Y", you have to:
1. Query the API for the list of rights the user has.
2. Query the API for the list of protection levels the page has.
3. Don't forget, of course, that the `autoconfirmed` and `sysop` protection levels aren't actually rights like any other protection level. They remain as aliases for "backwards compatibility" to the `editsemiprotected` and `editprotected` rights, respectively, and have nothing to do with the groups (a page that is `editprotected` is shown as `sysop` protected regardless of which groups have the `editprotected` right). So you have to translate those first.
4. Finally loop through the protection levels for the action you want to perform and check the user has all the necessary rights.
5. If there are cascading protection levels, also check the user has the `protect` right.

Fortunately in this instance, we can skip step 2 by using `mw.title.protectionLevels` and `mw.title.cascadingProtection` in lua (or the equivalent magic words), and outputting them as data attributes for JS to read.

Because of all that, it isn't practical to implement in the loader script (and regardless, delaying showing the tab with an API request isn't ideal), so instead the tab will have to remain, and the protection check will be done when the editor loads.

Ultimately, I'd prefer to still allow editing and instead save the changes to an editcopy page to be merged in by whoever can edit the main page.
The real difficulty there is how to handle merging in the editor. It would have to show some sort of notification that there are X unapproved changes, with a list of revisions that you can view diffs of and manually revert unwanted changes and "approve" the rest. That's getting rather more complicated, and would require proper human-readable diffs. If you edit without approving the editcopy changes, then you later need to handle merging those changes in, probably as if they were editconflicts.

Side note: even VE doesn't bother preventing you from editing protected pages, and just errors out on saving. VE _does_ hide the edit tab on directly protected pages (although directly navigating to the `veaction=edit` url will still let you edit). But on cascading protected pages, it (and the normal wikitext editing button) still act as if you can edit it. The wikitext editor at least makes the textarea read-only if you try to edit, but VE happily lets you edit a page you can't save, with the only indication of this being a small tooltip containing basically all the clutter that goes above the normal wikitext editor, which you will probably ignore (and even if you skim over it, the "you can't edit this" text is pretty unnoticeable underneath the bright yellow notice boxes).

**Comment by KnightMiner** [comment] 2015-09-12 18:04
Displaying the editcopy version of the sheet should be simple enough, and between Special:ComparePages and manual copying it would be easy enough to merge the changes, though still not ideal as we cannot easily tell what changed. A button to load the editcopy then go to the editing screen before saving it might help there.

A notification would be easy enough to generate based on timestamps, though if the main page is edited since then that would be thrown off.

As for approval, since we use the copy/paste form for most of our editcopies, I personally don't think it is required unless we add some form of approval extension to other pages, in which case it should already function using said extension.

Adding actual support for properly handling revisions into a human readable form would not be as simple, though wouldn't it be possible using a simple regex string matching on a diff from the [revisions property of the API](https://www.mediawiki.org/wiki/API:Revisions)? (I have no ideas for how to show the image diff, as there is really no way for it to detect which sprites changed without some sort of image comparing script, which I doubt would be fast or efficient).

**Closed as completed** 2015-10-30 05:46 UTC
